name: Angular CI/CD

on:
  push:
    branches: ["main"]
  # schedule: # here schedule time feature is not reliable because it not works on exact time defined in cron, so I will not use it for now, but you can use it if you want to run the workflow on schedule
  #     - cron: '*/5 * * * *' # Runs every 5 minutes
  #     - cron: '0 0 * * *' # Runs daily at 12:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24*
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Make script executable
        run: chmod +x scripts/create-env.sh

      - name: Generate environment file
        run: ./scripts/create-env.sh
        env:
            API_URL: ${{ vars.API_URL }}
            APP_TYPE: ${{ vars.APP_TYPE }}
            APP_VERSION: ${{ vars.APP_VERSION }}
            DEBUG_MODE: ${{ vars.DEBUG_MODE }}      

      - name: Build Project
        run: ng build --configuration production

      # Upload dist
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Download dist
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: dist/

      - name: Upload to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USER_NAME }}  
          password: ${{ secrets.PASSWORD }}
          source: "dist/*"
          target: "/home/mini_server_01/noor"
      - name: Notify Slack (Success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
          "text": "✅ Deployment Successful!\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref_name }}"
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack (Failure)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
          "text": "❌ Deployment Failed!\nRepo: ${{ github.repository }}"
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}